# Generated by Django 4.2.4 on 2023-08-30 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.TextField(blank=True),
        ),
    ]
